drop table Products;
drop table Stock;
drop table OrderDetails;
drop table Class;

CREATE TABLE Products (
prModelNo VARCHAR(15) NOT NULL UNIQUE CONSTRAINT prMdlNoPK PRIMARY KEY,
prName VARCHAR(25) NOT NULL,
prDescription VARCHAR(100) NOT NULL,
prPrice DECIMAL(6,2) NOT NULL,
classID INT(5) NOT NULL,
manufacturerID INT(5) NOT NULL,
minStockLevel INT(6) NOT NULL,
maxStockLevel INT(6)
);

CREATE TABLE OrderDetails (
orderID INT(10) NOT NULL CONSTRAINT orIDFK FOREIGN KEY REFERENCES Orders (orderID),
stockID INT(10) NOT NULL CONSTRAINT stIDFK FOREIGN KEY REFERENCES Stock (stockID),
odQuantity INT(3) NOT NULL,
CONSTRAINT orIDstIDPK PRIMARY KEY (orderID, stockID)
);

CREATE TABLE Stock (
stockID INT(10) AUTO_INCREMENT NOT NULL CONSTRAINT stIDPK PRIMARY KEY,
supplierID INT(10) NOT NULL CONSTRAINT supIDFK FOREIGN KEY REFERENCES Suppliers (supplierID),
prModelNo VARCHAR(15) NOT NULL CONSTRAINT prMdlNoFK FOREIGN KEY REFERENCES Products (prModelNo),
locationID INT(10) NOT NULL CONSTRAINT loIDFK FOREIGN KEY REFERENCES location (locationID),
stQuantity INT(7) NOT NULL
);
